Edited Error 404

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -3,8 +3,8 @@
 # world" page.
 
 if [[ $EUID -ne 0 ]]; then
-  echo "ERROR: You need to be root to run this script" 1>&2
-  exit 1
+    echo "ERROR: You need to be root to run this script" 1>&2
+    exit 1
 fi
 
 # Update the package list and install Nginx
@@ -41,6 +41,6 @@ rm /tmp/new_config
 service nginx start
 
 if [[ ! $? ]]; then
-  echo "ERROR: Failed to start Nginx" 1>&2
-  exit 1
+    echo "ERROR: Failed to start Nginx" 1>&2
+    exit 1
 fi
